### ISSUE TITLE
Request for review of minimal extension module

### ISSUE THREAD

**Issue by jougs** [nest/nest-extension-module#3]
In order to make it easier for users to write their own custom modules, I have now added a minimal version of the module example in the branch [minimal](https://github.com/nest/nest-extension-module/tree/minimal) of this repository, as it was discussed in the [last hackathon](https://github.com/nest/nest-simulator/wiki/NEST-Hackathon-01.07---03.07-2020).

I would especially like to ask
* @clinssen to give this a try in the context of [NESTML](https://gitbhub.com/nest/nestml)
* @terhorstd to have a look at the [`initialize.py`](https://github.com/nest/nest-extension-module/blob/minimal/initialize.py) script
* @gtrensch to scrutinize the build system (CMake and Travis)

Please comment below and/or send PRs if you find anything noteworthy.

I'm really sorry for this unconventional way of review, but I totally failed with bootstrapping this branch in a conceptually sane way because we already have so much code and history and all. As the diff between branches is not very useful in this case, my initial hope was to start from an empty branch and get the minimal module in via a PR that could be properly reviewed. This plan, however, failed in spectacular ways and I'm pretty much convinced that I have meanwhile seen all error messages Git has to offer when branches with different histories collide.

**Comment by jougs** [comment]
@clinssen, @terhorstd, @gtrensch: ping!

**Comment by jougs** [comment]
If you have nothing to say, we can as well just close this. In this sense: speak now or remain silent forever!

**Comment by clinssen** [comment]
Thanks for the reminder! Just some small points.

Would suggest to change line 12 of https://github.com/nest/nest-extension-module/blob/minimal/initialize.py from ``module_name += "Module"`` to ``module_name += "module"`` for consistency. File names are still using "my" rather than ``module_name``.

In the message "You can now add your custom source code files to the 'src' directory and use them within 'src/mymodule.h' and 'src/mymodule.cpp'.": what is meant by "use within"?

``cmake --Dwith-nest=<nest-prefix>/bin/nest-config ..`` should be ``cmake -Dwith-nest=<nest-prefix>/bin/nest-config ..``

**Comment by terhorstd** [comment]
I am fine with `initialize.py`, only minor point would be to add a doc-string to the file describing the rough outline what it's supposed to do in a few lines. (in a `initialize.py --help` style)

**Comment by jougs** [comment]
Replying to @clinssen's [comments](https://github.com/nest/nest-extension-module/issues/3#issuecomment-695840537):

> Would suggest to change line 12 of https://github.com/nest/nest-extension-module/blob/minimal/initialize.py from `module_name += "Module"` to `module_name += "module"` for consistency. File names are still using "my" rather than `module_name`.

My thinking was that the user supplied module names "MyModule" and just "My" both end up being the same module. However, as that might neither be obvious nor necessary, I have removed the mangling of the module name altogether and just directly use whatever the user supplies (fea37efd4). I reckon that keeping the file names untouched makes the script less prone to errors (e.g. if weird characters are used in the module name) and eases writing generic instructions that refer to them.

> In the message "You can now add your custom source code files to the 'src' directory and use them within 'src/mymodule.h' and 'src/mymodule.cpp'.": what is meant by "use within"?

I (hope I) have clarified the sentence in 8257bd11d by replacing "use" by "instantiate or register the contained components".
 
> `cmake --Dwith-nest=<nest-prefix>/bin/nest-config ..` should be `cmake -Dwith-nest=<nest-prefix>/bin/nest-config ..`

Fixed in 4c1a3104f together with making it consistent with NEST after https://github.com/nest/nest-simulator/pull/1721

> Note that the GitHub markdown rendering does not seem to like angle brackets in a header, so "for " just shows up as "for" in the README.

Fixed in 07c5facdb.

**Comment by jougs** [comment]
Replying to @terhorstd's [comment](https://github.com/nest/nest-extension-module/issues/3#issuecomment-6959840269):
> I am fine with `initialize.py`, only minor point would be to add a doc-string to the file describing the rough outline what it's supposed to do in a few lines. (in a `initialize.py --help` style)

I've added a `--help` option to the script in 84fccceb6.

**Comment by terhorstd** [comment]
LGTM

**Comment by jougs** [comment]
Originally, I thought that the `minimal` branch can not be properly tested using continuous integration, as it is not complete in the sense that it does not contain any neuron/synapse models or such. In an off-line discussion with @clinssen, however, we came to the conclusion that it should actually be possible to build the `minimal` branch in the form of an *empty* extension module after running `initialize.py`. 09728b0b5 consequently removes the interactive part of that script (namely the question if it shall continue or abort) and adds an examplary invocation to `travis_build.sh`. This means that the `minimal` branch is now [successfully checked in Travis CI](https://travis-ci.org/github/nest/nest-extension-module/builds/735821750). Yay!

**Comment by jougs** [comment]
With two positive reviews and all major issues addresses, I think that this issue can be closed. Again thanks for the review!
