### ISSUE TITLE
Remove SLI-related functionality from example module

### ISSUE THREAD

**Issue by jougs** [nest/nest-extension-module#4]
The possibility to provide custom SLI functions has previously been the only way to add new functions to NEST. With PyNEST in wide-spread use and the use of SLI slowly fading away, there is no longer a need for this. The SLI-related functionality should thus be removed from the module example in order to simplify the code and reduce the potential for confusion.

**Comment by heplesser** [comment]
:+1:

**Comment by Helveg** [comment]
Are there any plans to replace this with other sorts of custom functions from extension modules?

**Comment by jougs** [comment]
@Helveg: The easiest way for extending NEST and not going through SLI is to add functionality via a custom Python/Cython stub. Do you have a specific use case in mind?  Maybe we could add some example code somewhere.

**Comment by Helveg** [comment]
I'd like to have some functions on my extension module accessible to those who install them. Even if they're just silly wrappers like creating some preconfigured populations with specific connections. A specific usecase is one where we create a teaching signal per node so a form of plasticity with 3 populations involved and if we create N nodes of population A then N nodes of B and C need to be created and connected in the same way.

Something like this would be flashy:

```python
import nest
nest.Install('mymodule')
nest.mymodule.CreateTeachers(100)
```

**Comment by jougs** [comment]
Thanks for the explanation. Unfortunately, extension modules for NEST were never exposed in such a way (i.e. as submodules of `nest` on the Python level) and although I quite like the idea, I am afraid that it would require significant changes internally to make it so. Even with the possibility to add custom SLI functions it was quite a stretch to make those available to PyNEST. 

We are currently in the process of disentangling the NEST simulation kernel from the SLI interpreter in order to increase the maintainability and performance (by having less software layers between the user and the machine) and make NEST also usable as a stand-alone C++ library. It remains to be seen how we could support this kind of language-specific extensibility in the new language-independent framework.

The easiest solution right now is to add your Python code as a proper Python module to your NEST extension module and extend the `CMakeLists.txt` to build/install that code for the user. The invocation would then look more like this:

```python
import nest
import mymodule    # The nest.Install('mymodule') could be hidden in here

neurons = nest.Create('iaf_psc_alpha')
mymodule.SetNeurons(neurons)
mymodule.CreateTeachers(100)
```

**Comment by Helveg** [comment]
Ok, not a problem. Thanks for the explanation :)
